[theme]
base = "light"
primaryColor = "#0f172a"
backgroundColor = "#f8fafc"
secondaryBackgroundColor = "#ffffff"
textColor = "#0f172a"

[server]
maxMessageSize = 500
maxUploadSize = 500
enableStaticServing = true
